drop index ACT_HI_CASEINST.ACT_IDX_HI_CAS_I_CLOSE;
drop index ACT_HI_CASEINST.ACT_IDX_HI_CAS_I_BUSKEY;
drop index ACT_HI_CASEINST.ACT_IDX_HI_CAS_I_TENANT_ID;
drop index ACT_HI_CASEACTINST.ACT_IDX_HI_CAS_A_I_CREATE;
drop index ACT_HI_CASEACTINST.ACT_IDX_HI_CAS_A_I_END;
drop index ACT_HI_CASEACTINST.ACT_IDX_HI_CAS_A_I_COMP;
drop index ACT_HI_CASEACTINST.ACT_IDX_HI_CAS_A_I_TENANT_ID;

if exists (select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ACT_HI_CASEINST') drop table ACT_HI_CASEINST;
if exists (select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ACT_HI_CASEACTINST') drop table ACT_HI_CASEACTINST;
