drop index ACT_HI_CASEINST.ACT_IDX_HI_CAS_I_CLOSE;
drop index ACT_HI_CASEINST.ACT_IDX_HI_CAS_I_BUSKEY;

if exists (select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ACT_HI_CASEINST') drop table ACT_HI_CASEINST;
