package org.camunda.bpm.engine.test.standalone.rules.deploytest;
 
import org.camunda.bpm.engine.test.standalone.rules.Order
 
rule "OrderItemCountZeroOrLess"
     when
        order : Order( itemCount <= 0)
     then
     	order.setValid(false);          
end
 
rule "OrderItemCountGreaterThanZero"
     when
        order : Order( itemCount > 0)
     then
     	order.setValid(true);           
end