name: 'Extract JIRA links'
description: 'Extract JIRA ticket references from issue links and produces slack blocks that can be included in a slack message'
inputs:
  links:
    description: 'The links output of ../extract-issue-links'
    required: true
  issues:
    description: 'The issues output of ../extract-issue-links'
    required: true
  jira-project:
    description: 'JIRA Project to find links to'
    required: true
outputs:
  links-blocks:
    description: 'Rendering of the github issues and their matching JIRA links as Slack blocks (https://api.slack.com/reference/block-kit/blocks). Can be used to send as a message to slack.'
runs:
  using: 'node16'
  main: 'index.js'