camunda.bpm:
  admin-user:
    id: demo
    password: demo

# datasource configuration is required
spring.datasource:
  url: jdbc:h2:./camunda-h2-dbs/process-engine;TRACE_LEVEL_FILE=0;DB_CLOSE_ON_EXIT=FALSE
  driver-class-name: org.h2.Driver
  username: sa
  password: sa
