# This file defines the github labels that we use for pull requests (only)
# These are ci: and bot: labels. You can use this file to sync those labels
# with our repositories (see README)

# Bot labels
- name: "bot:java-dependency-tree"
  description: "When assigned to a PR, scans the code for Maven dependency changes and prints a diff."
  color: "D4C5F9"
- name: "bot:java-dependency-check"
  description: "When assigned to a PR, generates SBOMs for the PR and base branch and compares them."
  color: "D4C5F9"
  
# CI labels
- name: "ci:all-as"
  description: "Runs the builds for all application servers."
  color: "cccccc"
- name: "ci:all-db"
  description: "Runs the builds for all databases."
  color: "cccccc"
- name: "ci:cockroachdb"
  description: "Runs the builds for the CockroachDB database."
  color: "cccccc"
- name: "ci:db2"
  description: "Runs the builds for the DB2 database."
  color: "cccccc"
- name: "ci:default-build"
  description: "Runs the builds that have no explicit trigger (e.g. different history levels)."
  color: "cccccc"
- name: "ci:e2e"
  description: "Runs the frontend end-to-end tests."
  color: "cccccc"
- name: "ci:h2"
  description: "Runs the builds for the H2 database."
  color: "cccccc"
- name: "ci:jbosseap"
  description: "Runs the builds for the JBoss EAP application server."
  color: "cccccc"
- name: "ci:jdk"
  description: "Runs the builds for all supported Java versions."
  color: "cccccc"
- name: "ci:mariadb"
  description: "Runs the builds for the MariaDB database."
  color: "cccccc"
- name: "ci:migration"
  description: "Runs the process instance migration builds."
  color: "cccccc"
- name: "ci:mysql"
  description: "Runs the builds for the MySQL database."
  color: "cccccc"
- name: "ci:no-build"
  description: "Prevents any CI stage from running."
  color: "cccccc"
- name: "ci:oracle"
  description: "Runs the builds for the Oracle database."
  color: "cccccc"
- name: "ci:postgresql"
  description: "Runs the builds for the PostgreSQL database."
  color: "cccccc"
- name: "ci:rest-api"
  description: "Runs extra builds for the REST API (currently only WLS compatibility builds)."
  color: "cccccc"
- name: "ci:rolling-update"
  description: "Runs the rolling update builds."
  color: "cccccc"
- name: "ci:run"
  description: "Runs the integration tests for the Run distribution."
  color: "cccccc"
- name: "ci:spring-boot"
  description: "Runs the integration tests for the Spring Boot starter."
  color: "cccccc"
- name: "ci:sqlserver"
  description: "Runs the builds for the MS SQL Server database."
  color: "cccccc"
- name: "ci:tomcat"
  description: "Runs the builds for the Tomcat application server."
  color: "cccccc"
- name: "ci:webapp-integration"
  description: "Runs the webapp integration builds."
  color: "cccccc"
- name: "ci:weblogic"
  description: "Runs the builds for the Weblogic Application Server."
  color: "cccccc"
- name: "ci:websphere"
  description: "Runs the builds for the Websphere application server."
  color: "cccccc"
- name: "ci:wildfly"
  description: "Runs the builds for the Wildfly application server."
  color: "cccccc"
- name: "ci:skipTests"
  description: "Skips tests execution in Assembly and Distro-ee stages."
  color: "cccccc"
- name: "ci:distro"
  description: "Archives distro artifacts."
  color: "cccccc"
