import groovy.json.JsonSlurper

// https://github.com/camunda/jenkins-global-shared-library
// https://github.com/camunda/cambpm-jenkins-shared-library
@Library(['camunda-ci', 'cambpm-jenkins-shared-library']) _

def failedStageTypes = []

pipeline {
  agent none
  parameters {
    buildSelector(
        name: 'copyArtifactSelector',
        description: 'A build to take the artifacts from'
    )
    booleanParam defaultValue: true, description: '', name: 'STANDALONE'
    string defaultValue: '', description: 'The labels assigned to the CE pull request', name: 'PR_LABELS'
  }
  options {
    buildDiscarder(logRotator(numToKeepStr: '5')) //, artifactNumToKeepStr: '30'
  }
  triggers {
    pollSCM('H H(0-7) * * *')
  }
  stages {
    stage('Prepare') {
      when {
        expression { params.STANDALONE == false }
        beforeAgent true
      }
      agent {
        node {
          label 'centos-stable'
        }
      }
      steps {
        copyArtifacts(projectName: "cambpm-ce/cambpm-main/${env.BRANCH_NAME}", fingerprintArtifacts: true, selector: buildParameter('copyArtifactSelector'), optional: true)
        sh 'ls -al'
        stash name: "platform-stash-runtime", includes: ".m2/org/camunda/**/*-SNAPSHOT/**", excludes: "**/qa/**,**/*qa*/**,**/*.zip,**/*.tar.gz"
        stash name: "platform-stash-qa", includes: ".m2/org/camunda/bpm/**/qa/**/*-SNAPSHOT/**,.m2/org/camunda/bpm/**/*qa*/**/*-SNAPSHOT/**", excludes: "**/*.zip,**/*.tar.gz"
      }
    }
    stage('check-sql-scripts') {
      agent {
        node {
          label 'centos-stable'
        }
      }
      steps {
        sh '.ci/scripts/check-sql-scripts.sh'
      }
    }
    stage('H2 QA tests') {
      parallel {
        stage('sql-scripts-h2') {
          when {
            expression {
              withLabels('h2', 'all-db')
            }
            beforeAgent true
          }
          agent {
            node {
              label 'centos-stable'
            }
          }
          steps {
            catchError(stageResult: 'FAILURE') {
              withMaven(jdk: 'jdk-8-latest', maven: 'maven-3.2-latest', mavenSettingsConfig: 'camunda-maven-settings', options: [artifactsPublisher(disabled: true), junitPublisher(disabled: true)]) {
                runMaven(true, false, isQaStashEnabled('check-sql'), getMavenProfileDir('check-sql'), getMavenProfileCmd('check-sql') + cambpmGetDbProfiles('h2'))
              }
            }
          }
          post {
            failure {
              cambpmAddFailedStageType(failedStageTypes, 'check-sql')
            }
          }
        }
        stage('UPGRADE-databases-from-714-h2') {
          when {
            expression {
              withLabels('h2', 'all-db')
            }
            beforeAgent true
          }
          agent {
            node {
              label 'centos-stable'
            }
          }
          steps {
            catchError(stageResult: 'FAILURE') {
              withMaven(jdk: 'jdk-8-latest', maven: 'maven-3.2-latest', mavenSettingsConfig: 'camunda-maven-settings', options: [artifactsPublisher(disabled: true), junitPublisher(disabled: true)]) {
                runMaven(true, false, isQaStashEnabled('upgrade-db'), getMavenProfileDir('upgrade-db'), getMavenProfileCmd('upgrade-db') + cambpmGetDbProfiles('h2'))
              }
            }
          }
          post {
            always {
              cambpmPublishTestResult();
            }
            failure {
              cambpmAddFailedStageType(failedStageTypes, 'upgrade-db')
            }
          }
        }
        stage('UPGRADE-instance-migration-h2') {
          when {
            expression {
              withLabels('default-build', 'migration')
            }
            beforeAgent true
          }
          agent {
            node {
              label 'centos-stable'
            }
          }
          steps {
            catchError(stageResult: 'FAILURE') {
              withMaven(jdk: 'jdk-8-latest', maven: 'maven-3.2-latest', mavenSettingsConfig: 'camunda-maven-settings', options: [artifactsPublisher(disabled: true), junitPublisher(disabled: true)]) {
                runMaven(true, false, isQaStashEnabled('instance-migration'), getMavenProfileDir('instance-migration'), getMavenProfileCmd('instance-migration') + cambpmGetDbProfiles('h2'))
              }
            }
          }
          post {
            always {
              cambpmPublishTestResult();
            }
            failure {
              cambpmAddFailedStageType(failedStageTypes, 'instance-migration')
            }
          }
        }
        stage('UPGRADE-old-engine-from-714-h2') {
          when {
            expression {
              withLabels('h2', 'all-db')
            }
            beforeAgent true
          }
          agent {
            node {
              label 'centos-stable'
            }
          }
          steps {
            catchError(stageResult: 'FAILURE') {
              withMaven(jdk: 'jdk-8-latest', maven: 'maven-3.2-latest', mavenSettingsConfig: 'camunda-maven-settings', options: [artifactsPublisher(disabled: true), junitPublisher(disabled: true)]) {
                runMaven(true, false, isQaStashEnabled('old-engine'), getMavenProfileDir('old-engine'), getMavenProfileCmd('old-engine') + cambpmGetDbProfiles('h2'))
              }
            }
          }
          post {
            always {
              cambpmPublishTestResult();
            }
            failure {
              cambpmAddFailedStageType(failedStageTypes, 'old-engine')
            }
          }
        }
        stage('UPGRADE-rolling-update-h2') {
          when {
            expression {
              withLabels('rolling-update', 'default-build')
            }
            beforeAgent true
          }
          agent {
            node {
              label 'centos-stable'
            }
          }
          steps {
            catchError(stageResult: 'FAILURE') {
              withMaven(jdk: 'jdk-8-latest', maven: 'maven-3.2-latest', mavenSettingsConfig: 'camunda-maven-settings', options: [artifactsPublisher(disabled: true), junitPublisher(disabled: true)]) {
                runMaven(true, false, isQaStashEnabled('rolling-update'), getMavenProfileDir('rolling-update'), getMavenProfileCmd('rolling-update') + cambpmGetDbProfiles('h2'))
              }
            }
          }
          post {
            always {
              cambpmPublishTestResult();
            }
            failure {
              cambpmAddFailedStageType(failedStageTypes, 'rolling-update')
            }
          }
        }
        stage('PERFORMANCE-large-data-h2') {
          when {
            branch cambpmDefaultBranch();
            beforeAgent true
          }
          agent {
            node {
              label 'centos-stable'
            }
          }
          steps {
            catchError(stageResult: 'FAILURE') {
              withMaven(jdk: 'jdk-8-latest', maven: 'maven-3.2-latest', mavenSettingsConfig: 'camunda-maven-settings', options: [artifactsPublisher(disabled: true), junitPublisher(disabled: true)]) {
                runMaven(true, false, isQaStashEnabled('large-data-tests'), getMavenProfileDir('large-data-tests'), getMavenProfileCmd('large-data-tests') + cambpmGetDbProfiles('h2'))
              }
            }
          }
          post {
            always {
              cambpmPublishTestResult();
            }
            failure {
              cambpmAddFailedStageType(failedStageTypes, 'large-data-tests')
            }
          }
        }
      }
    }
    stage('QA DB tests') {
      matrix {
        axes {
          axis {
            name 'DB'
            values 'postgresql_96', 'postgresql_94', 'postgresql_107', 'postgresql_112', 'postgresql_122', 'cockroachdb_201', 'mariadb_100', 'mariadb_102', 'mariadb_103', 'mariadb_galera', 'mysql_57', 'oracle_11', 'oracle_12', 'oracle_18', 'oracle_19', 'db2_105', 'db2_111', 'sqlserver_2017', 'sqlserver_2019'
          }
          axis {
            name 'PROFILE'
            values 'check-sql', 'upgrade-db', 'instance-migration', 'old-engine', 'rolling-update', 'large-data-tests'
          }
        }
        when {
          expression {
            cambpmIsNotFailedStageType(failedStageTypes, env.PROFILE) && withLabels(getLabels(env.PROFILE)) && withDbLabels(env.DB)
          }
          beforeAgent true
        }
        agent {
          node {
            label env.DB
          }
        }
        stages {
          stage("QA test") {
            steps {
              echo("QA DB Test Stage: ${env.PROFILE}-${env.DB}")
              catchError(stageResult: 'FAILURE') {
                withMaven(jdk: 'jdk-8-latest', maven: 'maven-3.2-latest', mavenSettingsConfig: 'camunda-maven-settings', options: [artifactsPublisher(disabled: true), junitPublisher(disabled: true)]) {
                  runMaven(true, false, isQaStashEnabled(env.PROFILE), getMavenProfileDir(env.PROFILE), getMavenProfileCmd(env.PROFILE) + cambpmGetDbProfiles(DB) + " " + cambpmGetDbExtras(env.DB), true)
                }
              }
            }
            post {
              always {
                cambpmPublishTestResult();
              }
            }
          }
        }
      }
    }
    stage('JDKs') {
      matrix {
        axes {
          axis {
            name 'JDK'
            values 'openjdk-jdk-8-latest', 'openjdk-jdk-14-latest'
          }
        }
        when {
          expression {
            withLabels('default-build')
          }
          beforeAgent true
        }
        agent {
          node {
            label 'centos-stable'
          }
        }
        stages {
          stage('JDK') {
            steps {
              catchError(stageResult: 'FAILURE') {
                withMaven(jdk: env.JDK, maven: 'maven-3.2-latest', mavenSettingsConfig: 'camunda-maven-settings', options: [artifactsPublisher(disabled: true), junitPublisher(disabled: true)]) {
                  runMaven(true, false, false, '.', 'install source:jar source:test-jar -pl \'!webapps\',\'!distro/jbossas7/subsystem\' -Pdistro,distro-ce,distro-wildfly')
                }
              }
            }
            post {
              always {
                cambpmPublishTestResult();
              }
            }
          }
        }
      }
    }
  }
  post {
    changed {
      script {
        if (!agentDisconnected()){
          // send email if the slave disconnected
        }
      }
    }
    always {
      script {
        if (agentDisconnected()) {// Retrigger the build if the slave disconnected
          //currentBuild.result = 'ABORTED'
          //currentBuild.description = "Aborted due to connection error"
          build job: currentBuild.projectName, propagate: false, quietPeriod: 60, wait: false
        }
      }
    }
  }
}

void runMaven(boolean runtimeStash, boolean archivesStash, boolean qaStash, String directory, String cmd, boolean singleThreaded = false) {
  if (!params.STANDALONE && runtimeStash) unstash "platform-stash-runtime"
  if (!params.STANDALONE && archivesStash) unstash "platform-stash-archives"
  if (!params.STANDALONE && qaStash) unstash "platform-stash-qa"
  String forkCount = singleThreaded? "-DforkCount=1" : '';
  configFileProvider([configFile(fileId: 'maven-nexus-settings', variable: 'MAVEN_SETTINGS_XML')]) {
    sh("mvn -s \$MAVEN_SETTINGS_XML ${forkCount} ${cmd} -nsu -Dmaven.repo.local=\${WORKSPACE}/.m2 -B -f ${directory}/pom.xml")
  }
}


boolean withLabels(List labels) {
  if (params.STANDALONE && env.BRANCH_NAME != cambpmDefaultBranch() && pullRequest.labels.contains('no-build')) {
    return false;
  }

  if (env.BRANCH_NAME == cambpmDefaultBranch()) {
    return true;
  } else if (!params.STANDALONE) {
    for (l in labels) {
      if (new JsonSlurper().parseText(params.PR_LABELS).contains(l)) {
        return true;
      }
    }
  } else {
    for (l in labels) {
      if (pullRequest.labels.contains(l)) {
        return true;
      }
    }
  }
  return false;
}

boolean withLabels(String... labels) {
  return withLabels(Arrays.asList(labels));
}

boolean withDbLabels(String dbLabel) {
  return withLabels(cambpmGetDbType(dbLabel),'all-db');
}

String resolveMavenProfileInfo(String profile) {
  Map PROFILE_PATHS = [
      'check-sql': [
          directory: 'distro/sql-script/',
          command: 'install -Pcheck-sql,',
          qaStash: false,
          labels: ['all-db','db2','mysql','oracle','mariadb','sqlserver','postgresql']],
     'upgrade-db': [
          directory: 'qa/test-db-upgrade/',
          command: 'verify -Pupgrade-db,',
          qaStash: false,
          labels: ['all-db','db2','mysql','oracle','mariadb','sqlserver','postgresql']],
      'instance-migration': [
          directory: 'qa/test-db-instance-migration/',
          command: 'verify -Pinstance-migration,',
          qaStash: true,
          labels: []],
      'old-engine': [
          directory: 'qa/',
          command: 'verify -Pold-engine,',
          qaStash: false,
          labels: []],
      'rolling-update': [
          directory: 'qa/test-db-rolling-update/',
          command: 'verify -Prolling-update,',
          qaStash: true,
          labels: []],
      'large-data-tests': [
          directory: 'qa/large-data-tests/',
          command: 'verify -Plarge-data-tests,',
          qaStash: false,
          labels: []]
  ]

  return PROFILE_PATHS[profile]
}

String getMavenProfileCmd(String profile) {
  return resolveMavenProfileInfo(profile).command
}

String getMavenProfileDir(String profile) {
  return resolveMavenProfileInfo(profile).directory
}

boolean isQaStashEnabled(String profile) {
  return resolveMavenProfileInfo(profile).qaStash
}

String[] getLabels(String profile) {
  return resolveMavenProfileInfo(profile).labels
}