// https://github.com/camunda/jenkins-global-shared-library
// https://github.com/camunda/cambpm-jenkins-shared-library
@Library(['camunda-ci', 'cambpm-jenkins-shared-library@3690']) _

def failedStageTypes = []

pipeline {
  agent {
    node {
      label 'jenkins-job-runner'
    }
  }
  environment {
    LOGGER_LOG_LEVEL = 'DEBUG'
    MAVEN_VERSION = 'maven-3.8-latest'
    JDK_VERSION = 'jdk-11-latest'
  }
  parameters {
    booleanParam name: 'TRIGGERED_BY_UPSTREAM', defaultValue: false, description: 'Is the current build triggered in the scope of an upstream pipeline (pull request or default branch)'
    string name: 'UPSTREAM_PROJECT_NAME', defaultValue: '7.XX/cambpm-ce/cambpm-main/master', description: 'Not used on standalone runs. This property is passed by the upstream build that triggers this one.'
    string name: 'UPSTREAM_BUILD_NUMBER', defaultValue: '', description: 'Not used on standalone runs. This property is passed by the upstream build that triggers this one.'
    string name: 'PR_LABELS', defaultValue: '', description: 'The labels assigned to the CE pull request'
  }
  options {
    buildDiscarder(logRotator(numToKeepStr: '5'))
    disableConcurrentBuilds()
  }
  triggers {
    pollSCM('H H(0-3) * * *') // CE daily runs after EE daily and Sidetrack daily
  }
  stages {
    stage('Prepare') {
      when {
        expression {
          return params.TRIGGERED_BY_UPSTREAM
        }
      }
      steps {
        cambpmConditionalRetry([
          agentLabel: 'centos-stable',
          suppressErrors: false,
          runSteps: {
            cambpmCopyArtifacts(params.UPSTREAM_PROJECT_NAME, params.UPSTREAM_BUILD_NUMBER)
            cambpmStash("platform-stash-runtime",
                        ".m2/org/camunda/**/*-SNAPSHOT/**",
                        "**/qa/**,**/*qa*/**,**/*.zip,**/*.tar.gz")
            cambpmStash("platform-stash-qa",
                        ".m2/org/camunda/bpm/**/qa/**/*-SNAPSHOT/**,.m2/org/camunda/bpm/**/*qa*/**/*-SNAPSHOT/**",
                        "**/*.zip,**/*.tar.gz")
          }
        ])
      }
    }
    stage('Misc') {
      parallel {
        stage('check-sql-scripts') {
          when {
            expression {
              cambpmWithLabels('all-db','h2','db2','mysql','oracle','mariadb','sqlserver','postgresql','cockroachdb')
            }
          }
          steps {
            cambpmConditionalRetry([
              agentLabel: 'centos-stable',
              runSteps: {
                sh(label: 'Check SQL scripts', script: '.ci/scripts/check-sql-scripts.sh')
              }
            ])
          }
        }
        stage('stage-javadocs') {
          when {
            branch cambpmDefaultBranch();
          }
          steps {
            cambpmConditionalRetry([
              agentLabel : 'centos-stable',
              runSteps   : {
                cambpmRunMaven('.',
                  "package javadoc:javadoc javadoc:aggregate -Pdistro,distro-wildfly,distro-webjar,javadocs -pl " +
                  "'!distro/wildfly/modules,!distro/wildfly26/modules,!engine-rest/engine-rest-openapi' -DskipTests=true -Dskip.frontend.build=true",
                  withNpm: true,
                  jdkVersion: 'jdk-17-latest')
              },
              postSuccess: {
                def projectVersion = env.JOB_NAME.split('/')[0] + "-SNAPSHOT"
                cambpmPublishDocs("\"target/site/apidocs/\"", projectVersion, "javadoc")
              }
            ])
          }
        }
        stage('stage-restapi-docs') {
          when {
            branch cambpmDefaultBranch();
          }
          steps {
            cambpmConditionalRetry([
              agentLabel : 'centos-stable',
              runSteps   : {
                cambpmRunMaven('./engine-rest',
                  "package -Dmaven.test.skip -pl '!engine-rest,!assembly'",
                  withNpm: true,
                  jdkVersion: 'jdk-11-latest')
              },
              postSuccess: {
                def projectVersion = env.JOB_NAME.split('/')[0] + "-SNAPSHOT"
                cambpmPublishDocs("\"engine-rest/docs/target/index.html\"", projectVersion, "rest")
              }
            ])
          }
        }
        stage('Trigger Docker CE GHA') {
          when {
            expression {
              // trigger docker CE build only on the master branch
              env.BRANCH_NAME == cambpmDefaultBranch() && cambpmIsDevelopmentVersion()
            }
          }
          agent {
            kubernetes {
              cloud "kubernetes"
              label "${utils.envPrefix()}ci-infra-camunda-cloud-build_${env.JOB_BASE_NAME.take(15)}-${env.BUILD_ID}"
              defaultContainer 'alpine'
              yaml org.camunda.helper.Podspec.getAgentPodspec(this, 'alpine-small', [
                  useStableNodePool: false
              ])
            }
          }
          options {
            timeout(time: 45, unit: 'MINUTES')
          }
          environment {
            // define helper script input arguments
            INPUT_OWNER = 'camunda'
            INPUT_REPO = 'docker-camunda-bpm-platform'
            // ensure that the GHA trigger works for maintenance branches as well
            INPUT_REF = cambpmGetDockerRepoBranch()
            INPUT_WORKFLOW_FILE_NAME = 'build-test-and-publish-ce.yml'
            INPUT_WAIT_INPUT_WAIT_WORKFLOW = 'true'
          }
          steps {
            catchError(stageResult: 'FAILURE') {
              script {
                camundaGitHubWorkflowDispatch.prepareStep()
                camundaGitHubWorkflowDispatch.dispatchStep('github-cambpm-ci-pipeline-app')
              }
            }
          }
        }
      }
    }
    stage('Standalone QA tests') {
      parallel {
        stage('sql-scripts-h2') {
          when {
            expression {
              cambpmWithLabels('h2', 'all-db')
            }
          }
          steps {
            cambpmConditionalRetry([
              agentLabel: 'h2',
              runSteps: {
                cambpmRunMavenByStageType('sql-scripts', 'h2')
              },
              postFailure: {
                cambpmAddFailedStageType(failedStageTypes, 'sql-scripts')
              }
            ])
          }
        }
        stage('UPGRADE-instance-migration-h2') {
          when {
            expression {
              cambpmWithLabels('default-build', 'migration')
            }
          }
          steps {
            cambpmConditionalRetry([
              agentLabel: 'h2',
              runSteps: {
                cambpmRunMavenByStageType('instance-migration', 'h2')
              },
              postFailure: {
                cambpmPublishTestResult()
                cambpmAddFailedStageType(failedStageTypes, 'instance-migration')
              }
            ])
          }
        }
        stage('UPGRADE-old-engine-h2') {
          when {
            expression {
              cambpmWithLabels('h2', 'all-db')
            }
          }
          steps {
            cambpmConditionalRetry([
              agentLabel: 'h2',
              runSteps: {
                cambpmRunMavenByStageType('old-engine', 'h2')
              },
              postFailure: {
                cambpmPublishTestResult()
                cambpmAddFailedStageType(failedStageTypes, 'old-engine')
              }
            ])
          }
        }
        stage('UPGRADE-rolling-update-h2') {
          when {
            expression {
              cambpmWithLabels('rolling-update', 'default-build')
            }
          }
          steps {
            cambpmConditionalRetry([
              agentLabel: 'h2',
              runSteps: {
                cambpmRunMavenByStageType('rolling-update', 'h2')
              },
              postFailure: {
                cambpmPublishTestResult()
                cambpmAddFailedStageType(failedStageTypes, 'rolling-update')
              }
            ])
          }
        }
        stage('PERFORMANCE-large-data-h2') {
          when {
            expression {
              cambpmWithLabels()
            }
          }
          steps {
            cambpmConditionalRetry([
              agentLabel: 'h2',
              runSteps: {
                cambpmRunMavenByStageType('large-data-tests', 'h2')
              },
              postFailure: {
                cambpmPublishTestResult()
                cambpmAddFailedStageType(failedStageTypes, 'large-data-tests')
              }
            ])
          }
        }
      }
    }
    stage('QA DB tests') {
      steps {
        script {
          // see the .ci/config/matrices.yaml for the stage generation values
          // see .ci/config/stage-types.yaml for the stage configurations
          parallel(cambpmGetMatrixStages('daily-stages', failedStageTypes, { stageInfo ->
            List allowedStageLabels = stageInfo.allowedLabels
            String dbLabel = stageInfo.nodeType
            return cambpmWithLabels(allowedStageLabels.minus('cockroachdb'), cambpmGetDbType(dbLabel))
          }))
        }
      }
    }
    stage('JDKs') {
      steps {
        script {
          // see the .ci/config/matrices.yaml for the stage generation values
          // see .ci/config/stage-types.yaml for the stage configurations
          parallel(cambpmGetMatrixStages('jdk-ce-stages', failedStageTypes, { stageInfo ->
            return cambpmWithLabels('default-build', 'jdk')
          }))
        }
      }
    }
  }
  post {
    changed {
      script {
        if (!agentDisconnected()){
          cambpmSendEmailNotification()
        }
      }
    }
    always {
      cambpmWithSpanAttributes()
    }
  }
}
