name: 'Extract github issue links'
description: 'Extracts links from github issues that match the following criteria: 1) Use the HTTP(S) protocol; 2) End with a JIRA issue identifier (e.g. FOO-1234). Note that this may produce false positives.'
inputs:
  versions:
    description: 'Versions to include when searching for github issues. Should be a comma-separated list of version identifiers, e.g. "7.18.0, 7.17.2, 7.16.6"'
    required: true
  version-prefix:
    description: 'The prefix for the labels that identify versions'
    required: true
  repo-token:
    description: 'Github access token'
    required: true
outputs:
  links:
    description: 'A JSON string of the logical structure "github issue id" => ["link 1", "link 2", ..]. Use common/utils/collection-utils.js for parsing into a JS Map'
  links-reverse:
    description: 'A JSON string of the logical structure  "link" => ["github issue link 1", "github issue link 2", ..]. Use common/utils/collection-utils.js for parsing into a JS Map'
  issues:
    description: 'A JSON string of the logical structure "github issue id" => { .. a selection github issue properties ..}. Use common/utils/collection-utils.js for parsing into a JS Map'
runs:
  using: 'node16'
  main: 'index.js'