name: 'Copy issue'
description: 'Copies an issue.'
inputs:
  issue:
    description: 'The number of the issue to copy.'
    required: true
  deep-copy:
    description: 'Boolean. Specify if a deep copy should be made, i.e. if any issues linked in the description should also be copied. Supports only the #123 linking style, not full HTTP links. Copies only one level of linked issues.'
    required: true
  version-prefix:
    description: 'The prefix of the labels that mark the fix versions.'
    required: true
  version:
    description: 'The new fix version (without the prefix).'
    required: true
  repo-token:
    description: 'Github access token'
    required: true
runs:
  using: 'node16'
  main: 'index.js'