name: Copy issue

on: 
  workflow_dispatch:
    inputs:
      issue:
        description: 'Number of the issue to copy'
        required: true
      version:
        description: 'The fix version to assign to the new issues (without label prefix)'
        required: true
      
jobs:
  call-reusable-flow:
    uses: camunda/automation-platform-github-actions/.github/workflows/copy-issue.yml@main
    with: 
      issue: ${{ github.event.inputs.issue }}
      version: ${{ github.event.inputs.version }}
