name: Java Dependency Check

on:
  pull_request:
    types: [ labeled ]

jobs:
  call-reusable-flow:
    uses: camunda/automation-platform-github-actions/.github/workflows/java-dependency-check.yml@add-gpl-cp-license
    if: ${{ github.event.label.name == 'bot:java-dependency-check' }}
    with:
      ref: add-gpl-cp-license
    secrets: inherit
