name: Synchronize label colors

on:
  label:
    types: 
      - created

jobs:
  call-reusable-flow:
    uses: camunda/automation-platform-github-actions/.github/workflows/sync-label-colors.yml@main    
